[package]
name = "dirswitch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
skim = "0.9.4"
config = { version = "0.11.0", features = ["yaml"] }
dirs-next = "2.0.0"
serde = { version = "1.0", features = ["derive"] }
shellexpand = "2.1.0"
