name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - mrjones2014
body:
  - type: checkboxes
    id: similar-issues
    attributes:
      label: Similar Issues
      options:
        - label: Before filing, I have searched for similar issues.
    validations:
      required: true
  - type: markdown
    id: desc
    attributes:
      value: |
        # Description
    validations:
      required: true
  - type: input
    id: os-version
    attributes:
      label: Operating System + Version (if macOS, please specify if it's Apple ARM silicon)
    validations:
      required: true
  - type: markdown
    id: shell-version
    attributes:
      value: |
        # Shell + Version (`bash --version`, `zsh --version`, `fish --version`, please use a code block)
    validations:
      required: true
  - type: markdown
    id: min-config
    attributes:
      value: |
        # Minimal Configuration to Reproduce (`.bashrc`, `.zshrc`, `config.fish`, please use a code block)
    validations:
      required: true
  - type: markdown
    id: details
    attributes:
      value: |
        # Additinal Details
    validations:
      required: true
