name: Feature Request
description: Request a feature
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - mrjones2014
body:
  - type: checkboxes
    id: similar-issues
    attributes:
      options:
        - label: Before filing, I have searched for similar issues.
    validations:
      required: true
  - type: markdown
    id: desc
    attributes:
      value: |
        # Description
    validations:
      required: true
  - type: markdown
    id: use-case
    attributes:
      value: |
        # Use Case

        Please describe why the feature would be useful.
    validations:
      required: true
