name: Feature Request
description: Request a feature
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - mrjones2014
body:
  - type: checkboxes
    attributes:
      label: Similar Issues
      description: Before filing, I have searched for similar issues.
  - type: markdown
    attributes:
      label: Description
  - type: markdown
    attributes:
      label: Use Case
      description: Describe why this feature would be useful.
